_extends: .github

repository:
  name: noip-containerized
  description: Containerized No-IP cURL request to update your DDNS A records.
  homepage: https://github.com/bjd2385/noip-containerized
  topics: noip, no-ip, ddns
