version: 2.1


executors:
  docker:
    machine:
      image: ubuntu-2204:2022.07.1


jobs:
  docker-github:
    resource_class: medium
    executor: docker
    parameters:
      image-name:
        description: Name of the image.
        default: ''
        type: string
      tag:
        description: Name of the tag for the image.
        default: develop
        type: string
      commit-tag:
        description: Whether or not to push an additional tag to the registry with the commit hash as the tag.
        default: false
        type: boolean
      args:
        description: Additional args string to add to the build command. (E.g., '--build-arg HELLO=WORLD'.)
        default: ''
        type: string
      path:
        description: Path to the Dockerfile.
        default: .
        type: string
    steps:
      - checkout
      - run:
          name: Login to ghcr.io
          command: |+
            echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - run:
          name: Build and push tag
          command: |+
            docker build << parameters.path >> -t << parameters.image-name >>:<< parameters.tag >> << parameters.args >>
            docker push << parameters.image-name >>:<< parameters.tag >>
      - when:
          condition: << parameters.commit-tag >>
          steps:
            - run:
                name: Push commit tag
                command: |+
                  docker tag << parameters.image-name >>:<< parameters.tag >> << parameters.image-name >>:$CIRCLE_SHA1
                  docker push << parameters.image-name >>:$CIRCLE_SHA1


workflows:
  docker:
    jobs:
      - docker-github:
          image-name: ghcr.io/bjd2385/noip
          commit-tag: true
          # Project-level env vars.
          args: --build-arg USER_PASSWORD=$USER_PASS
          context: github
